#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const yargs = require("yargs");
const powerTree = require("./powerTree.js");

// show version
try {
  if (Object.prototype.hasOwnProperty.call(yargs.argv, "v")) {
    const json = JSON.parse(
      fs.readFileSync(path.join(__dirname, "package.json"))
    );
    console.log("version:", json.version);
    return;
  }
} catch (e) {
  console.error(
    `miss 'package.json' file, please download powerTree again and do not delete this file`
  );
  return;
}

// show help
if (Object.prototype.hasOwnProperty.call(yargs.argv, "h")) {
  console.log(
    "usage: p-tree [path(default .)] [number(padWidth)] [-c(colorful)] [-e(extend)]"
  );
  return;
}

const colorModal = Boolean(
  Object.prototype.hasOwnProperty.call(yargs.argv, "c")
);
const extendsModal = Boolean(
  Object.prototype.hasOwnProperty.call(yargs.argv, "e")
);

if (yargs.argv._.length === 0) {
  powerTree.listFiles(colorModal, extendsModal, ".");
} else {
  powerTree.listFiles(colorModal, extendsModal, ...yargs.argv._);
}
